services:
  - type: web
    name: telegram-spin-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false      # Make sure to set this in Render dashboard
      - key: TELEGRAM_CHANNEL_ID
        sync: false      # Make sure to set this in Render dashboard
      - key: MONGODB_URI
        sync: false      # Make sure to set this in Render dashboard
      - key: WEBHOOK_URL
        sync: false      # Make sure to set this in Render dashboard
    healthCheckPath: /   # Ensure you have a health check endpoint in your app
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
    runtime: node20
